name: Test frontend cookiecutter template generation & usage

on:
  push:
    branches:
      - frontend

jobs:
  test-run-template:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Cookiecutter
      run: pip install cookiecutter

    - name: Generate frontend template
      run: cookiecutter frontend --no-input
    
    # - name: Run tests
    #   run: |
    #     cd vuejs_template
    #     npm install