name: Run Flake8, Black, ISort

on:
  pull_request:
    branches: [develop, next, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install linters
        run: pip install flake8 black isort

      - name: Run Flake8
        run: flake8 app tests
        if: always()

      - name: Run black
        run: black app tests --check
        if: always()

      - name: Run isort
        run: isort app tests --check-only
        if: always()
