#{% raw %}
name: Lint & Type Check & Unit Tests

on:
  pull_request:
    branches: [develop, uat, main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: ["16.14.0"]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --save-dev
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test:unit
#{% endraw %}